name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: castor
      - name: 'composer install'
        run: 'composer update --prefer-stable'
      - name: 'install tools'
        run: 'castor tools:install'
      - name: 'run tests (for generated classes)'
        run: vendor/bin/phpunit
      - name: 'php-cs-fixer check'
        run: 'castor tools:cs-check'
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions:  ['8.2', '8.3']
    name: tests-${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-versions }}-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-stable
      - name: tests
        run: vendor/bin/phpunit
  tests-lowest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer-lowest
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-lowest-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-lowest --prefer-stable
      - name: tests
        run: vendor/bin/phpunit
